"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { getCourseLearningPlanDashboard, taskStatusLabel, taskTypeLabel, type LearningPlanSummary, type LearningTask } from "@/lib/api";

export function CoursePlanStatus({ courseId }: { courseId: string }) {
  const [data, setData] = useState<{ draft_plan: LearningPlanSummary | null; pending_plan: LearningPlanSummary | null; active_plan: LearningPlanSummary | null; current_task: LearningTask | null; today_tasks: LearningTask[] } | null>(null);
  useEffect(() => { void getCourseLearningPlanDashboard(courseId).then(setData).catch(() => setData(null)); }, [courseId]);
  const draft = data?.draft_plan; const pending = data?.pending_plan; const active = data?.active_plan;
  if (draft) return <section className="rounded-2xl border border-sky-200 bg-sky-50/60 p-4"><p className="font-semibold text-foreground">有一份计划等待继续编辑</p><p className="mt-1 text-sm text-muted-foreground">“{draft.plan.title}”还没有开始执行，补充或调整后再确认即可。</p><Link href={`/learning-plans/${draft.plan.id}/edit`} className="mt-3 inline-flex rounded-lg bg-brand px-3 py-2 text-sm font-semibold text-brand-foreground">继续编辑</Link></section>;
  if (pending) return <section className="rounded-2xl border border-amber-200 bg-amber-50/60 p-4"><p className="font-semibold text-foreground">学习计划等待确认</p><p className="mt-1 text-sm text-muted-foreground">我们已经准备好“{pending.plan.title}”，确认后即可开始。</p><Link href={`/learning-plans/${pending.plan.id}/review`} className="mt-3 inline-flex rounded-lg bg-brand px-3 py-2 text-sm font-semibold text-brand-foreground">查看并确认</Link></section>;
  if (active) { const total = active.task_count || 0; const task = data?.current_task; return <section className="rounded-2xl border border-brand/20 bg-brand-muted/25 p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-foreground">当前学习计划</p><p className="mt-1 text-sm text-muted-foreground">{active.plan.title} · 已完成 {active.completed_task_count}/{total} 项</p></div><span className="rounded-full bg-card px-2.5 py-1 text-xs font-medium text-brand">进行中</span></div>{task ? <div className="mt-4 rounded-xl border border-brand/15 bg-card/70 px-3 py-3"><p className="text-xs font-medium text-brand">当前任务 · {taskTypeLabel[task.task_type]}</p><p className="mt-1 truncate text-sm font-semibold text-foreground">{task.title}</p><p className="mt-1 text-xs text-muted-foreground">{taskStatusLabel[task.status]}{task.estimated_minutes ? ` · 约 ${task.estimated_minutes} 分钟` : ""}</p></div> : <p className="mt-4 rounded-xl bg-card/70 px-3 py-3 text-sm text-muted-foreground">当前没有可执行任务，请在计划中安排下一步。</p>}<Link href={`/learning-plans/${active.plan.id}`} className="mt-4 inline-flex rounded-lg border border-brand/30 bg-card px-3 py-2 text-sm font-semibold text-brand hover:bg-brand-muted">查看详细计划</Link></section>; }
  return <section className="rounded-2xl border border-dashed border-border p-4"><p className="font-semibold text-foreground">制定学习计划</p><p className="mt-1 text-sm text-muted-foreground">根据本学习空间的真实章节生成可调整草稿。</p><div className="mt-3 flex gap-4"><Link href={`/learning-plans/ai/new?courseId=${courseId}`} className="text-sm font-semibold text-brand hover:underline">AI 生成学习计划</Link><Link href={`/learning-plans/new?courseId=${courseId}`} className="text-sm font-medium text-muted-foreground hover:text-foreground">手动创建</Link></div></section>;
}
