"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { listLearningPlans, planStatusLabel, type LearningPlan } from "@/lib/api";

type Tab = "active" | "pending" | "paused" | "completed" | "cancelled" | "draft";
const tabs: Array<[Tab, string]> = [["active", "进行中"], ["pending", "待确认"], ["paused", "已暂停"], ["completed", "已完成"], ["cancelled", "已取消"], ["draft", "草稿"]];

export function PlanCenter() {
  const [plans, setPlans] = useState<LearningPlan[]>([]); const [tab, setTab] = useState<Tab>("active"); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = () => { setLoading(true); setError(null); void listLearningPlans().then(setPlans).catch(() => setError("暂时无法连接学习计划服务。请确认项目后端已启动后重试。")).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => plans.filter((plan) => tab === "draft" ? plan.status === "DRAFT" || plan.status === "CHANGES_REQUESTED" : tab === "pending" ? plan.status === "PENDING_APPROVAL" : tab === "active" ? plan.status === "ACTIVE" : tab === "paused" ? plan.status === "PAUSED" : tab === "completed" ? plan.status === "COMPLETED" : plan.status === "CANCELLED"), [plans, tab]);
  return <main className="mx-auto min-h-screen max-w-5xl bg-background px-4 py-8 sm:px-6"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-muted-foreground">学习计划中心</p><h1 className="mt-1 text-2xl font-bold text-foreground">把计划变成每天可完成的一步</h1></div><div className="flex items-center gap-4"><Link href="/learning-plans/new" className="inline-flex h-10 items-center rounded-full bg-brand px-4 text-sm font-semibold text-brand-foreground">新建学习计划</Link><Link href="/" className="text-sm font-medium text-brand hover:underline">返回首页</Link></div></header><nav className="mt-6 flex gap-2 overflow-x-auto border-b border-border/70" aria-label="学习计划分类">{tabs.map(([key, label]) => <button type="button" key={key} onClick={() => setTab(key)} className={`shrink-0 border-b-2 px-3 py-3 text-sm font-medium ${tab === key ? "border-brand text-brand" : "border-transparent text-muted-foreground"}`}>{label}</button>)}</nav>{loading ? <p className="py-10 text-sm text-muted-foreground">正在加载学习计划…</p> : error ? <div className="mt-6 rounded-2xl bg-destructive/10 p-4 text-sm text-destructive">{error}<button className="ml-3 underline" onClick={load}>重试</button></div> : visible.length === 0 ? <section className="mt-8 rounded-2xl border border-dashed border-border p-8 text-center"><h2 className="font-semibold">{tab === "draft" ? "没有需要继续编辑的计划" : tab === "pending" ? "没有等待确认的计划" : tab === "active" ? "当前没有进行中的学习计划" : "还没有可显示的计划"}</h2><p className="mt-2 text-sm text-muted-foreground">可以新建学习计划，或从学习空间让 AI 为你生成草稿。</p></section> : <div className="mt-6 grid gap-4 sm:grid-cols-2">{visible.map((plan) => <PlanCard key={plan.id} plan={plan} />)}</div>}</main>;
}

function PlanCard({ plan }: { plan: LearningPlan }) { const review = plan.status === "PENDING_APPROVAL"; const editable = plan.status === "DRAFT" || plan.status === "CHANGES_REQUESTED"; const target = review ? `/learning-plans/${plan.id}/review` : editable ? `/learning-plans/${plan.id}/edit` : `/learning-plans/${plan.id}`; return <article className="rounded-2xl border border-border/70 bg-card p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-brand-muted px-2.5 py-1 text-xs font-medium text-brand">{planStatusLabel[plan.status]}</span><span className="text-xs text-muted-foreground">{plan.source === "AI" ? "AI 生成" : plan.source === "USER" ? "自行创建" : "计划模板"}</span></div><h2 className="mt-4 text-lg font-semibold text-foreground">{plan.title}</h2><p className="mt-2 text-sm text-muted-foreground">目标日期：{plan.target_date || "暂未设定"}</p><p className="mt-1 text-sm text-muted-foreground">每天约 {plan.available_minutes_per_day || "—"} 分钟</p><Link href={target} className="mt-5 inline-flex h-9 items-center rounded-lg bg-brand px-4 text-sm font-semibold text-brand-foreground">{review ? "查看并确认" : editable ? "继续编辑" : plan.status === "PAUSED" ? "查看并恢复" : "查看计划"}</Link></article>; }
